dist: stretch
sudo: required

services: 
  - docker

before_install:
  - sudo curl -fsSL https://get.docker.com/ | sh
  - if [ -e /usr/local/bin/docker-compose ]; then sudo rm /usr/local/bin/docker-compose; fi
  - sudo curl -L https://github.com/docker/compose/releases/download/${TRAVIS_DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo docker-compose build --no-cache --force-rm
  - sudo docker-compose up -d fl-maps-db
  - sudo docker-compose up -d fl-maps

language: node_js

node_js:
  - "8.14.0"

install:
  - "npm install"

script:
  - "npm test"
